### ISSUE TITLE
👋 Nemo

### ISSUE THREAD

**Issue by giautm** [coolcorexix/navigating-after-fetching-data-with-react-router#1]
Hi, the example looks great. But with the new version for React-Router, they also support Data.loader. It was extracted from Remix core to become a part of RR lib.

https://reactrouter.com/en/main/start/tutorial#loading-data

**Comment by giautm** [comment]
kk, sorry about my typo

**Comment by coolcorexix** [comment]
@giautm woah, that's pretty handy. I better find more chances to work on react router v6 to explore more of its possibilities. Thank you for giving me a hint.
